### ISSUE TITLE
Installation instructions for Linux needs adjustements

### ISSUE THREAD

**Issue by ljulliar** [dbanay/Smalltalk#2]
Hi Dan,

First of all what a fantastic job you have done. Really! I always dreamt of running the original ST-80 images again.... You made my deram come true.

One minor adjustement in the installation instructions for Linux. Here is what I did:
```
$ git clone repo
$ cd Smalltalk
$ ./configure
-bash: ./configure: No such file or directory
$ cd linux
$ make
$ make install
make: *** No rule to make target 'install'.  Stop.
$ ./Smalltalk 
```
it opens Smalltalk 80 just fine!! Yeah...

So in other words I could not run ./configure, nor make install on Linux.

Besides on my Debian distro you can also simply install the SDL 2 dev package and it works fine
`$ sudo apt install libsdl2-dev`

**Comment by dbanay** [comment]
Sorry for the confusion.  The configure/build steps were for SDL and they way I wrote it  made it seem like you had to do that for the Smalltalk project. Edited the README to correct this!  Thank you.
