### ISSUE TITLE
Eating all CPU

### ISSUE THREAD

**Issue by ljulliar** [dbanay/Smalltalk#3]
Hi Dan,

I also noticed that once Smalltalk is running it keeps eating almost 100% of the CPU. I guess there must be some kind of event polling loop running forever, right ?

**Comment by dbanay** [comment]
Yep, that's exactly what it's doing. You can either use the -vsync command line option to sync to your display refresh rate, which has the effect of idling a bit or you can use the command line option -delay with a value like 8 and you should see an reduction of CPU usage.
